namespace MerinoOne.SupplierPortal.Infrastructure.Persistence.Seed;

/// <summary>
/// Reference (geo + currency) seed data consumed by <see cref="MasterSeeder.SeedReferenceDataAsync"/>.
/// Curated dev/demo set: the full active ISO 4217 currency list, a working set of countries (each linked to a
/// currency present in <see cref="Currencies"/>), every Indian state + union territory, the major cities, and a
/// representative spread of PIN codes per city. Codes are the natural keys (deterministic ids derive from them):
///   Currency.Code = ISO 4217 alpha; Country.Code = ISO 3166-1 alpha-2; State.Code = short subdivision code;
///   City.Code = "{StateCode}-{abbrev}" (kept unique across India); PostalCode.Code = the 6-digit PIN.
/// Full all-India city/PIN coverage (~8k towns / ~19k PINs) is intentionally NOT hardcoded — load it via a bulk
/// import when needed; this set keeps the seeder fast and the address geo cascade demonstrable.
/// </summary>
public static partial class MasterSeeder
{
    public record CurrencySpec(string Code, string Desc, string Iso, string Symbol);
    public record CountrySpec(string Code, string Desc, string Iso2, string Iso3, string Tel, string CurrencyCode);
    public record StateSpec(string Code, string Desc, string CountryCode);
    public record CitySpec(string Code, string Desc, string CountryCode, string? StateCode);
    public record PostalSpec(string Code, string Area, string CountryCode, string? StateCode, string? CityCode);

    // ── Currencies — active ISO 4217 alpha set ────────────────────────────────────────────────
    public static readonly IReadOnlyList<CurrencySpec> Currencies = new[]
    {
        new CurrencySpec("AED", "UAE Dirham", "AED", "د.إ"),
        new CurrencySpec("AFN", "Afghan Afghani", "AFN", "؋"),
        new CurrencySpec("ALL", "Albanian Lek", "ALL", "L"),
        new CurrencySpec("AMD", "Armenian Dram", "AMD", "֏"),
        new CurrencySpec("ANG", "Netherlands Antillean Guilder", "ANG", "ƒ"),
        new CurrencySpec("AOA", "Angolan Kwanza", "AOA", "Kz"),
        new CurrencySpec("ARS", "Argentine Peso", "ARS", "$"),
        new CurrencySpec("AUD", "Australian Dollar", "AUD", "$"),
        new CurrencySpec("AWG", "Aruban Florin", "AWG", "ƒ"),
        new CurrencySpec("AZN", "Azerbaijani Manat", "AZN", "₼"),
        new CurrencySpec("BAM", "Bosnia-Herzegovina Convertible Mark", "BAM", "KM"),
        new CurrencySpec("BBD", "Barbadian Dollar", "BBD", "$"),
        new CurrencySpec("BDT", "Bangladeshi Taka", "BDT", "৳"),
        new CurrencySpec("BGN", "Bulgarian Lev", "BGN", "лв"),
        new CurrencySpec("BHD", "Bahraini Dinar", "BHD", ".د.ب"),
        new CurrencySpec("BIF", "Burundian Franc", "BIF", "FBu"),
        new CurrencySpec("BMD", "Bermudian Dollar", "BMD", "$"),
        new CurrencySpec("BND", "Brunei Dollar", "BND", "$"),
        new CurrencySpec("BOB", "Bolivian Boliviano", "BOB", "Bs."),
        new CurrencySpec("BRL", "Brazilian Real", "BRL", "R$"),
        new CurrencySpec("BSD", "Bahamian Dollar", "BSD", "$"),
        new CurrencySpec("BTN", "Bhutanese Ngultrum", "BTN", "Nu."),
        new CurrencySpec("BWP", "Botswana Pula", "BWP", "P"),
        new CurrencySpec("BYN", "Belarusian Ruble", "BYN", "Br"),
        new CurrencySpec("BZD", "Belize Dollar", "BZD", "$"),
        new CurrencySpec("CAD", "Canadian Dollar", "CAD", "$"),
        new CurrencySpec("CDF", "Congolese Franc", "CDF", "FC"),
        new CurrencySpec("CHF", "Swiss Franc", "CHF", "Fr"),
        new CurrencySpec("CLP", "Chilean Peso", "CLP", "$"),
        new CurrencySpec("CNY", "Chinese Yuan Renminbi", "CNY", "¥"),
        new CurrencySpec("COP", "Colombian Peso", "COP", "$"),
        new CurrencySpec("CRC", "Costa Rican Colón", "CRC", "₡"),
        new CurrencySpec("CUP", "Cuban Peso", "CUP", "$"),
        new CurrencySpec("CVE", "Cape Verdean Escudo", "CVE", "$"),
        new CurrencySpec("CZK", "Czech Koruna", "CZK", "Kč"),
        new CurrencySpec("DJF", "Djiboutian Franc", "DJF", "Fdj"),
        new CurrencySpec("DKK", "Danish Krone", "DKK", "kr"),
        new CurrencySpec("DOP", "Dominican Peso", "DOP", "$"),
        new CurrencySpec("DZD", "Algerian Dinar", "DZD", "دج"),
        new CurrencySpec("EGP", "Egyptian Pound", "EGP", "£"),
        new CurrencySpec("ERN", "Eritrean Nakfa", "ERN", "Nfk"),
        new CurrencySpec("ETB", "Ethiopian Birr", "ETB", "Br"),
        new CurrencySpec("EUR", "Euro", "EUR", "€"),
        new CurrencySpec("FJD", "Fijian Dollar", "FJD", "$"),
        new CurrencySpec("FKP", "Falkland Islands Pound", "FKP", "£"),
        new CurrencySpec("GBP", "Pound Sterling", "GBP", "£"),
        new CurrencySpec("GEL", "Georgian Lari", "GEL", "₾"),
        new CurrencySpec("GHS", "Ghanaian Cedi", "GHS", "₵"),
        new CurrencySpec("GIP", "Gibraltar Pound", "GIP", "£"),
        new CurrencySpec("GMD", "Gambian Dalasi", "GMD", "D"),
        new CurrencySpec("GNF", "Guinean Franc", "GNF", "FG"),
        new CurrencySpec("GTQ", "Guatemalan Quetzal", "GTQ", "Q"),
        new CurrencySpec("GYD", "Guyanese Dollar", "GYD", "$"),
        new CurrencySpec("HKD", "Hong Kong Dollar", "HKD", "$"),
        new CurrencySpec("HNL", "Honduran Lempira", "HNL", "L"),
        new CurrencySpec("HTG", "Haitian Gourde", "HTG", "G"),
        new CurrencySpec("HUF", "Hungarian Forint", "HUF", "Ft"),
        new CurrencySpec("IDR", "Indonesian Rupiah", "IDR", "Rp"),
        new CurrencySpec("ILS", "Israeli New Shekel", "ILS", "₪"),
        new CurrencySpec("INR", "Indian Rupee", "INR", "₹"),
        new CurrencySpec("IQD", "Iraqi Dinar", "IQD", "ع.د"),
        new CurrencySpec("IRR", "Iranian Rial", "IRR", "﷼"),
        new CurrencySpec("ISK", "Icelandic Króna", "ISK", "kr"),
        new CurrencySpec("JMD", "Jamaican Dollar", "JMD", "$"),
        new CurrencySpec("JOD", "Jordanian Dinar", "JOD", "د.ا"),
        new CurrencySpec("JPY", "Japanese Yen", "JPY", "¥"),
        new CurrencySpec("KES", "Kenyan Shilling", "KES", "KSh"),
        new CurrencySpec("KGS", "Kyrgyzstani Som", "KGS", "с"),
        new CurrencySpec("KHR", "Cambodian Riel", "KHR", "៛"),
        new CurrencySpec("KMF", "Comorian Franc", "KMF", "CF"),
        new CurrencySpec("KPW", "North Korean Won", "KPW", "₩"),
        new CurrencySpec("KRW", "South Korean Won", "KRW", "₩"),
        new CurrencySpec("KWD", "Kuwaiti Dinar", "KWD", "د.ك"),
        new CurrencySpec("KYD", "Cayman Islands Dollar", "KYD", "$"),
        new CurrencySpec("KZT", "Kazakhstani Tenge", "KZT", "₸"),
        new CurrencySpec("LAK", "Lao Kip", "LAK", "₭"),
        new CurrencySpec("LBP", "Lebanese Pound", "LBP", "ل.ل"),
        new CurrencySpec("LKR", "Sri Lankan Rupee", "LKR", "₨"),
        new CurrencySpec("LRD", "Liberian Dollar", "LRD", "$"),
        new CurrencySpec("LSL", "Lesotho Loti", "LSL", "L"),
        new CurrencySpec("LYD", "Libyan Dinar", "LYD", "ل.د"),
        new CurrencySpec("MAD", "Moroccan Dirham", "MAD", "د.م."),
        new CurrencySpec("MDL", "Moldovan Leu", "MDL", "L"),
        new CurrencySpec("MGA", "Malagasy Ariary", "MGA", "Ar"),
        new CurrencySpec("MKD", "Macedonian Denar", "MKD", "ден"),
        new CurrencySpec("MMK", "Myanmar Kyat", "MMK", "K"),
        new CurrencySpec("MNT", "Mongolian Tögrög", "MNT", "₮"),
        new CurrencySpec("MOP", "Macanese Pataca", "MOP", "P"),
        new CurrencySpec("MRU", "Mauritanian Ouguiya", "MRU", "UM"),
        new CurrencySpec("MUR", "Mauritian Rupee", "MUR", "₨"),
        new CurrencySpec("MVR", "Maldivian Rufiyaa", "MVR", ".ރ"),
        new CurrencySpec("MWK", "Malawian Kwacha", "MWK", "MK"),
        new CurrencySpec("MXN", "Mexican Peso", "MXN", "$"),
        new CurrencySpec("MYR", "Malaysian Ringgit", "MYR", "RM"),
        new CurrencySpec("MZN", "Mozambican Metical", "MZN", "MT"),
        new CurrencySpec("NAD", "Namibian Dollar", "NAD", "$"),
        new CurrencySpec("NGN", "Nigerian Naira", "NGN", "₦"),
        new CurrencySpec("NIO", "Nicaraguan Córdoba", "NIO", "C$"),
        new CurrencySpec("NOK", "Norwegian Krone", "NOK", "kr"),
        new CurrencySpec("NPR", "Nepalese Rupee", "NPR", "₨"),
        new CurrencySpec("NZD", "New Zealand Dollar", "NZD", "$"),
        new CurrencySpec("OMR", "Omani Rial", "OMR", "﷼"),
        new CurrencySpec("PAB", "Panamanian Balboa", "PAB", "B/."),
        new CurrencySpec("PEN", "Peruvian Sol", "PEN", "S/"),
        new CurrencySpec("PGK", "Papua New Guinean Kina", "PGK", "K"),
        new CurrencySpec("PHP", "Philippine Peso", "PHP", "₱"),
        new CurrencySpec("PKR", "Pakistani Rupee", "PKR", "₨"),
        new CurrencySpec("PLN", "Polish Złoty", "PLN", "zł"),
        new CurrencySpec("PYG", "Paraguayan Guaraní", "PYG", "₲"),
        new CurrencySpec("QAR", "Qatari Riyal", "QAR", "﷼"),
        new CurrencySpec("RON", "Romanian Leu", "RON", "lei"),
        new CurrencySpec("RSD", "Serbian Dinar", "RSD", "дин."),
        new CurrencySpec("RUB", "Russian Ruble", "RUB", "₽"),
        new CurrencySpec("RWF", "Rwandan Franc", "RWF", "FRw"),
        new CurrencySpec("SAR", "Saudi Riyal", "SAR", "﷼"),
        new CurrencySpec("SBD", "Solomon Islands Dollar", "SBD", "$"),
        new CurrencySpec("SCR", "Seychellois Rupee", "SCR", "₨"),
        new CurrencySpec("SDG", "Sudanese Pound", "SDG", "ج.س."),
        new CurrencySpec("SEK", "Swedish Krona", "SEK", "kr"),
        new CurrencySpec("SGD", "Singapore Dollar", "SGD", "$"),
        new CurrencySpec("SHP", "Saint Helena Pound", "SHP", "£"),
        new CurrencySpec("SLE", "Sierra Leonean Leone", "SLE", "Le"),
        new CurrencySpec("SOS", "Somali Shilling", "SOS", "S"),
        new CurrencySpec("SRD", "Surinamese Dollar", "SRD", "$"),
        new CurrencySpec("SSP", "South Sudanese Pound", "SSP", "£"),
        new CurrencySpec("STN", "São Tomé and Príncipe Dobra", "STN", "Db"),
        new CurrencySpec("SVC", "Salvadoran Colón", "SVC", "₡"),
        new CurrencySpec("SYP", "Syrian Pound", "SYP", "£"),
        new CurrencySpec("SZL", "Swazi Lilangeni", "SZL", "L"),
        new CurrencySpec("THB", "Thai Baht", "THB", "฿"),
        new CurrencySpec("TJS", "Tajikistani Somoni", "TJS", "ЅМ"),
        new CurrencySpec("TMT", "Turkmenistani Manat", "TMT", "m"),
        new CurrencySpec("TND", "Tunisian Dinar", "TND", "د.ت"),
        new CurrencySpec("TOP", "Tongan Paʻanga", "TOP", "T$"),
        new CurrencySpec("TRY", "Turkish Lira", "TRY", "₺"),
        new CurrencySpec("TTD", "Trinidad and Tobago Dollar", "TTD", "$"),
        new CurrencySpec("TWD", "New Taiwan Dollar", "TWD", "NT$"),
        new CurrencySpec("TZS", "Tanzanian Shilling", "TZS", "TSh"),
        new CurrencySpec("UAH", "Ukrainian Hryvnia", "UAH", "₴"),
        new CurrencySpec("UGX", "Ugandan Shilling", "UGX", "USh"),
        new CurrencySpec("USD", "United States Dollar", "USD", "$"),
        new CurrencySpec("UYU", "Uruguayan Peso", "UYU", "$U"),
        new CurrencySpec("UZS", "Uzbekistani Som", "UZS", "soʻm"),
        new CurrencySpec("VES", "Venezuelan Bolívar Soberano", "VES", "Bs."),
        new CurrencySpec("VND", "Vietnamese Đồng", "VND", "₫"),
        new CurrencySpec("VUV", "Vanuatu Vatu", "VUV", "VT"),
        new CurrencySpec("WST", "Samoan Tālā", "WST", "T"),
        new CurrencySpec("XAF", "Central African CFA Franc", "XAF", "FCFA"),
        new CurrencySpec("XCD", "East Caribbean Dollar", "XCD", "$"),
        new CurrencySpec("XOF", "West African CFA Franc", "XOF", "CFA"),
        new CurrencySpec("XPF", "CFP Franc", "XPF", "₣"),
        new CurrencySpec("YER", "Yemeni Rial", "YER", "﷼"),
        new CurrencySpec("ZAR", "South African Rand", "ZAR", "R"),
        new CurrencySpec("ZMW", "Zambian Kwacha", "ZMW", "ZK"),
        new CurrencySpec("ZWL", "Zimbabwean Dollar", "ZWL", "$"),
    };

    // ── Countries — working set (each CurrencyCode exists in Currencies above) ─────────────────
    public static readonly IReadOnlyList<CountrySpec> Countries = new[]
    {
        new CountrySpec("IN", "India", "IN", "IND", "91", "INR"),
        new CountrySpec("US", "United States", "US", "USA", "1", "USD"),
        new CountrySpec("GB", "United Kingdom", "GB", "GBR", "44", "GBP"),
        new CountrySpec("AE", "United Arab Emirates", "AE", "ARE", "971", "AED"),
        new CountrySpec("AU", "Australia", "AU", "AUS", "61", "AUD"),
        new CountrySpec("BD", "Bangladesh", "BD", "BGD", "880", "BDT"),
        new CountrySpec("BH", "Bahrain", "BH", "BHR", "973", "BHD"),
        new CountrySpec("BR", "Brazil", "BR", "BRA", "55", "BRL"),
        new CountrySpec("BT", "Bhutan", "BT", "BTN", "975", "BTN"),
        new CountrySpec("CA", "Canada", "CA", "CAN", "1", "CAD"),
        new CountrySpec("CH", "Switzerland", "CH", "CHE", "41", "CHF"),
        new CountrySpec("CN", "China", "CN", "CHN", "86", "CNY"),
        new CountrySpec("DE", "Germany", "DE", "DEU", "49", "EUR"),
        new CountrySpec("DK", "Denmark", "DK", "DNK", "45", "DKK"),
        new CountrySpec("EG", "Egypt", "EG", "EGY", "20", "EGP"),
        new CountrySpec("ES", "Spain", "ES", "ESP", "34", "EUR"),
        new CountrySpec("FR", "France", "FR", "FRA", "33", "EUR"),
        new CountrySpec("HK", "Hong Kong", "HK", "HKG", "852", "HKD"),
        new CountrySpec("ID", "Indonesia", "ID", "IDN", "62", "IDR"),
        new CountrySpec("IE", "Ireland", "IE", "IRL", "353", "EUR"),
        new CountrySpec("IT", "Italy", "IT", "ITA", "39", "EUR"),
        new CountrySpec("JP", "Japan", "JP", "JPN", "81", "JPY"),
        new CountrySpec("KE", "Kenya", "KE", "KEN", "254", "KES"),
        new CountrySpec("KR", "South Korea", "KR", "KOR", "82", "KRW"),
        new CountrySpec("KW", "Kuwait", "KW", "KWT", "965", "KWD"),
        new CountrySpec("LK", "Sri Lanka", "LK", "LKA", "94", "LKR"),
        new CountrySpec("MM", "Myanmar", "MM", "MMR", "95", "MMK"),
        new CountrySpec("MX", "Mexico", "MX", "MEX", "52", "MXN"),
        new CountrySpec("MY", "Malaysia", "MY", "MYS", "60", "MYR"),
        new CountrySpec("NG", "Nigeria", "NG", "NGA", "234", "NGN"),
        new CountrySpec("NL", "Netherlands", "NL", "NLD", "31", "EUR"),
        new CountrySpec("NO", "Norway", "NO", "NOR", "47", "NOK"),
        new CountrySpec("NP", "Nepal", "NP", "NPL", "977", "NPR"),
        new CountrySpec("NZ", "New Zealand", "NZ", "NZL", "64", "NZD"),
        new CountrySpec("OM", "Oman", "OM", "OMN", "968", "OMR"),
        new CountrySpec("PH", "Philippines", "PH", "PHL", "63", "PHP"),
        new CountrySpec("PK", "Pakistan", "PK", "PAK", "92", "PKR"),
        new CountrySpec("PL", "Poland", "PL", "POL", "48", "PLN"),
        new CountrySpec("PT", "Portugal", "PT", "PRT", "351", "EUR"),
        new CountrySpec("QA", "Qatar", "QA", "QAT", "974", "QAR"),
        new CountrySpec("RU", "Russia", "RU", "RUS", "7", "RUB"),
        new CountrySpec("SA", "Saudi Arabia", "SA", "SAU", "966", "SAR"),
        new CountrySpec("SE", "Sweden", "SE", "SWE", "46", "SEK"),
        new CountrySpec("SG", "Singapore", "SG", "SGP", "65", "SGD"),
        new CountrySpec("TH", "Thailand", "TH", "THA", "66", "THB"),
        new CountrySpec("TR", "Türkiye", "TR", "TUR", "90", "TRY"),
        new CountrySpec("VN", "Vietnam", "VN", "VNM", "84", "VND"),
        new CountrySpec("ZA", "South Africa", "ZA", "ZAF", "27", "ZAR"),
    };

    // ── States + Union Territories of India (ISO 3166-2:IN subdivisions, "IN-" prefix dropped) ──
    public static readonly IReadOnlyList<StateSpec> States = new[]
    {
        new StateSpec("AP", "Andhra Pradesh", "IN"),
        new StateSpec("AR", "Arunachal Pradesh", "IN"),
        new StateSpec("AS", "Assam", "IN"),
        new StateSpec("BR", "Bihar", "IN"),
        new StateSpec("CG", "Chhattisgarh", "IN"),
        new StateSpec("GA", "Goa", "IN"),
        new StateSpec("GJ", "Gujarat", "IN"),
        new StateSpec("HR", "Haryana", "IN"),
        new StateSpec("HP", "Himachal Pradesh", "IN"),
        new StateSpec("JH", "Jharkhand", "IN"),
        new StateSpec("KA", "Karnataka", "IN"),
        new StateSpec("KL", "Kerala", "IN"),
        new StateSpec("MP", "Madhya Pradesh", "IN"),
        new StateSpec("MH", "Maharashtra", "IN"),
        new StateSpec("MN", "Manipur", "IN"),
        new StateSpec("ML", "Meghalaya", "IN"),
        new StateSpec("MZ", "Mizoram", "IN"),
        new StateSpec("NL", "Nagaland", "IN"),
        new StateSpec("OD", "Odisha", "IN"),
        new StateSpec("PB", "Punjab", "IN"),
        new StateSpec("RJ", "Rajasthan", "IN"),
        new StateSpec("SK", "Sikkim", "IN"),
        new StateSpec("TN", "Tamil Nadu", "IN"),
        new StateSpec("TG", "Telangana", "IN"),
        new StateSpec("TR", "Tripura", "IN"),
        new StateSpec("UP", "Uttar Pradesh", "IN"),
        new StateSpec("UK", "Uttarakhand", "IN"),
        new StateSpec("WB", "West Bengal", "IN"),
        new StateSpec("AN", "Andaman and Nicobar Islands", "IN"),
        new StateSpec("CH", "Chandigarh", "IN"),
        new StateSpec("DH", "Dadra and Nagar Haveli and Daman and Diu", "IN"),
        new StateSpec("DL", "Delhi", "IN"),
        new StateSpec("JK", "Jammu and Kashmir", "IN"),
        new StateSpec("LA", "Ladakh", "IN"),
        new StateSpec("LD", "Lakshadweep", "IN"),
        new StateSpec("PY", "Puducherry", "IN"),
    };

    // ── Major Indian cities (code = "{StateCode}-{abbrev}", unique across the country) ──────────
    public static readonly IReadOnlyList<CitySpec> Cities = new[]
    {
        new CitySpec("AP-VSKP", "Visakhapatnam", "IN", "AP"),
        new CitySpec("AP-VJA", "Vijayawada", "IN", "AP"),
        new CitySpec("AR-ITA", "Itanagar", "IN", "AR"),
        new CitySpec("AS-GHY", "Guwahati", "IN", "AS"),
        new CitySpec("BR-PAT", "Patna", "IN", "BR"),
        new CitySpec("CG-RAI", "Raipur", "IN", "CG"),
        new CitySpec("GA-PNJ", "Panaji", "IN", "GA"),
        new CitySpec("GJ-AMD", "Ahmedabad", "IN", "GJ"),
        new CitySpec("GJ-SRT", "Surat", "IN", "GJ"),
        new CitySpec("GJ-BRD", "Vadodara", "IN", "GJ"),
        new CitySpec("HR-GGN", "Gurugram", "IN", "HR"),
        new CitySpec("HR-FBD", "Faridabad", "IN", "HR"),
        new CitySpec("HP-SML", "Shimla", "IN", "HP"),
        new CitySpec("JH-RAN", "Ranchi", "IN", "JH"),
        new CitySpec("JH-JSR", "Jamshedpur", "IN", "JH"),
        new CitySpec("KA-BLR", "Bengaluru", "IN", "KA"),
        new CitySpec("KA-MYS", "Mysuru", "IN", "KA"),
        new CitySpec("KA-MNG", "Mangaluru", "IN", "KA"),
        new CitySpec("KL-TVM", "Thiruvananthapuram", "IN", "KL"),
        new CitySpec("KL-COK", "Kochi", "IN", "KL"),
        new CitySpec("KL-CCJ", "Kozhikode", "IN", "KL"),
        new CitySpec("MP-BHO", "Bhopal", "IN", "MP"),
        new CitySpec("MP-IND", "Indore", "IN", "MP"),
        new CitySpec("MH-MUM", "Mumbai", "IN", "MH"),
        new CitySpec("MH-PUN", "Pune", "IN", "MH"),
        new CitySpec("MH-NAG", "Nagpur", "IN", "MH"),
        new CitySpec("MN-IMF", "Imphal", "IN", "MN"),
        new CitySpec("ML-SHL", "Shillong", "IN", "ML"),
        new CitySpec("MZ-AJL", "Aizawl", "IN", "MZ"),
        new CitySpec("NL-KOH", "Kohima", "IN", "NL"),
        new CitySpec("OD-BBS", "Bhubaneswar", "IN", "OD"),
        new CitySpec("OD-CTC", "Cuttack", "IN", "OD"),
        new CitySpec("PB-LDH", "Ludhiana", "IN", "PB"),
        new CitySpec("PB-ASR", "Amritsar", "IN", "PB"),
        new CitySpec("RJ-JAI", "Jaipur", "IN", "RJ"),
        new CitySpec("RJ-JDH", "Jodhpur", "IN", "RJ"),
        new CitySpec("RJ-UDR", "Udaipur", "IN", "RJ"),
        new CitySpec("SK-GTK", "Gangtok", "IN", "SK"),
        new CitySpec("TN-MAA", "Chennai", "IN", "TN"),
        new CitySpec("TN-CBE", "Coimbatore", "IN", "TN"),
        new CitySpec("TN-IXM", "Madurai", "IN", "TN"),
        new CitySpec("TG-HYD", "Hyderabad", "IN", "TG"),
        new CitySpec("TG-WGL", "Warangal", "IN", "TG"),
        new CitySpec("TR-IXA", "Agartala", "IN", "TR"),
        new CitySpec("UP-LKO", "Lucknow", "IN", "UP"),
        new CitySpec("UP-KNP", "Kanpur", "IN", "UP"),
        new CitySpec("UP-NOI", "Noida", "IN", "UP"),
        new CitySpec("UP-VNS", "Varanasi", "IN", "UP"),
        new CitySpec("UK-DDN", "Dehradun", "IN", "UK"),
        new CitySpec("WB-CCU", "Kolkata", "IN", "WB"),
        new CitySpec("WB-HWH", "Howrah", "IN", "WB"),
        new CitySpec("WB-SIL", "Siliguri", "IN", "WB"),
        new CitySpec("AN-IXZ", "Port Blair", "IN", "AN"),
        new CitySpec("CH-CHD", "Chandigarh", "IN", "CH"),
        new CitySpec("DH-DMN", "Daman", "IN", "DH"),
        new CitySpec("DL-NDL", "New Delhi", "IN", "DL"),
        new CitySpec("DL-DEL", "Delhi", "IN", "DL"),
        new CitySpec("JK-SXR", "Srinagar", "IN", "JK"),
        new CitySpec("JK-IXJ", "Jammu", "IN", "JK"),
        new CitySpec("LA-IXL", "Leh", "IN", "LA"),
        new CitySpec("LD-KAV", "Kavaratti", "IN", "LD"),
        new CitySpec("PY-PNY", "Puducherry", "IN", "PY"),
    };

    // ── Representative PIN codes (real area names; mapped to the seeded city/state/country) ──────
    public static readonly IReadOnlyList<PostalSpec> PostalCodes = new[]
    {
        // Maharashtra
        new PostalSpec("400001", "Fort", "IN", "MH", "MH-MUM"),
        new PostalSpec("400002", "Kalbadevi", "IN", "MH", "MH-MUM"),
        new PostalSpec("400005", "Colaba", "IN", "MH", "MH-MUM"),
        new PostalSpec("400020", "Churchgate", "IN", "MH", "MH-MUM"),
        new PostalSpec("400050", "Bandra West", "IN", "MH", "MH-MUM"),
        new PostalSpec("400053", "Andheri West", "IN", "MH", "MH-MUM"),
        new PostalSpec("400070", "Kurla", "IN", "MH", "MH-MUM"),
        new PostalSpec("411001", "Pune GPO", "IN", "MH", "MH-PUN"),
        new PostalSpec("411004", "Deccan Gymkhana", "IN", "MH", "MH-PUN"),
        new PostalSpec("411014", "Viman Nagar", "IN", "MH", "MH-PUN"),
        new PostalSpec("411038", "Kothrud", "IN", "MH", "MH-PUN"),
        new PostalSpec("440001", "Nagpur GPO", "IN", "MH", "MH-NAG"),
        new PostalSpec("440010", "Dharampeth", "IN", "MH", "MH-NAG"),
        // Delhi
        new PostalSpec("110001", "Connaught Place", "IN", "DL", "DL-NDL"),
        new PostalSpec("110003", "Lodi Road", "IN", "DL", "DL-NDL"),
        new PostalSpec("110011", "New Delhi", "IN", "DL", "DL-NDL"),
        new PostalSpec("110006", "Chandni Chowk", "IN", "DL", "DL-DEL"),
        new PostalSpec("110007", "Civil Lines", "IN", "DL", "DL-DEL"),
        new PostalSpec("110092", "Shahdara", "IN", "DL", "DL-DEL"),
        // Karnataka
        new PostalSpec("560001", "Bengaluru GPO", "IN", "KA", "KA-BLR"),
        new PostalSpec("560034", "Koramangala", "IN", "KA", "KA-BLR"),
        new PostalSpec("560066", "Whitefield", "IN", "KA", "KA-BLR"),
        new PostalSpec("560100", "Electronic City", "IN", "KA", "KA-BLR"),
        new PostalSpec("570001", "Mysuru", "IN", "KA", "KA-MYS"),
        new PostalSpec("575001", "Mangaluru", "IN", "KA", "KA-MNG"),
        // Tamil Nadu
        new PostalSpec("600001", "Parrys", "IN", "TN", "TN-MAA"),
        new PostalSpec("600002", "Anna Salai", "IN", "TN", "TN-MAA"),
        new PostalSpec("600017", "T Nagar", "IN", "TN", "TN-MAA"),
        new PostalSpec("600040", "Anna Nagar", "IN", "TN", "TN-MAA"),
        new PostalSpec("641001", "Coimbatore", "IN", "TN", "TN-CBE"),
        new PostalSpec("625001", "Madurai", "IN", "TN", "TN-IXM"),
        // Telangana
        new PostalSpec("500001", "Hyderabad GPO", "IN", "TG", "TG-HYD"),
        new PostalSpec("500016", "Begumpet", "IN", "TG", "TG-HYD"),
        new PostalSpec("500032", "Gachibowli", "IN", "TG", "TG-HYD"),
        new PostalSpec("500081", "Madhapur", "IN", "TG", "TG-HYD"),
        new PostalSpec("506002", "Warangal", "IN", "TG", "TG-WGL"),
        // West Bengal
        new PostalSpec("700001", "BBD Bagh", "IN", "WB", "WB-CCU"),
        new PostalSpec("700016", "Park Street", "IN", "WB", "WB-CCU"),
        new PostalSpec("700019", "Ballygunge", "IN", "WB", "WB-CCU"),
        new PostalSpec("700091", "Bidhannagar (Salt Lake)", "IN", "WB", "WB-CCU"),
        new PostalSpec("711101", "Howrah", "IN", "WB", "WB-HWH"),
        new PostalSpec("734001", "Siliguri", "IN", "WB", "WB-SIL"),
        // Gujarat
        new PostalSpec("380001", "Ahmedabad", "IN", "GJ", "GJ-AMD"),
        new PostalSpec("380015", "Ambawadi", "IN", "GJ", "GJ-AMD"),
        new PostalSpec("395003", "Surat", "IN", "GJ", "GJ-SRT"),
        new PostalSpec("390001", "Vadodara", "IN", "GJ", "GJ-BRD"),
        // Uttar Pradesh
        new PostalSpec("226001", "Hazratganj", "IN", "UP", "UP-LKO"),
        new PostalSpec("226010", "Gomti Nagar", "IN", "UP", "UP-LKO"),
        new PostalSpec("208001", "Kanpur", "IN", "UP", "UP-KNP"),
        new PostalSpec("201301", "Noida", "IN", "UP", "UP-NOI"),
        new PostalSpec("221001", "Varanasi", "IN", "UP", "UP-VNS"),
        // Rajasthan
        new PostalSpec("302001", "Jaipur GPO", "IN", "RJ", "RJ-JAI"),
        new PostalSpec("302017", "Malviya Nagar", "IN", "RJ", "RJ-JAI"),
        new PostalSpec("342001", "Jodhpur", "IN", "RJ", "RJ-JDH"),
        new PostalSpec("313001", "Udaipur", "IN", "RJ", "RJ-UDR"),
        // Kerala
        new PostalSpec("695001", "Thiruvananthapuram", "IN", "KL", "KL-TVM"),
        new PostalSpec("682001", "Ernakulam", "IN", "KL", "KL-COK"),
        new PostalSpec("682024", "Kakkanad", "IN", "KL", "KL-COK"),
        new PostalSpec("673001", "Kozhikode", "IN", "KL", "KL-CCJ"),
        // Madhya Pradesh
        new PostalSpec("462001", "Bhopal", "IN", "MP", "MP-BHO"),
        new PostalSpec("452001", "Indore", "IN", "MP", "MP-IND"),
        // Bihar
        new PostalSpec("800001", "Patna", "IN", "BR", "BR-PAT"),
        // Odisha
        new PostalSpec("751001", "Bhubaneswar", "IN", "OD", "OD-BBS"),
        new PostalSpec("753001", "Cuttack", "IN", "OD", "OD-CTC"),
        // Punjab
        new PostalSpec("141001", "Ludhiana", "IN", "PB", "PB-LDH"),
        new PostalSpec("143001", "Amritsar", "IN", "PB", "PB-ASR"),
        // Haryana
        new PostalSpec("122001", "Gurugram", "IN", "HR", "HR-GGN"),
        new PostalSpec("121001", "Faridabad", "IN", "HR", "HR-FBD"),
        // Andhra Pradesh
        new PostalSpec("530001", "Visakhapatnam", "IN", "AP", "AP-VSKP"),
        new PostalSpec("520001", "Vijayawada", "IN", "AP", "AP-VJA"),
        // Assam
        new PostalSpec("781001", "Guwahati", "IN", "AS", "AS-GHY"),
        // Jharkhand
        new PostalSpec("834001", "Ranchi", "IN", "JH", "JH-RAN"),
        new PostalSpec("831001", "Jamshedpur", "IN", "JH", "JH-JSR"),
        // Chhattisgarh
        new PostalSpec("492001", "Raipur", "IN", "CG", "CG-RAI"),
        // Uttarakhand
        new PostalSpec("248001", "Dehradun", "IN", "UK", "UK-DDN"),
        // Himachal Pradesh
        new PostalSpec("171001", "Shimla", "IN", "HP", "HP-SML"),
        // Goa
        new PostalSpec("403001", "Panaji", "IN", "GA", "GA-PNJ"),
        // Chandigarh
        new PostalSpec("160001", "Chandigarh", "IN", "CH", "CH-CHD"),
        // Jammu & Kashmir
        new PostalSpec("190001", "Srinagar", "IN", "JK", "JK-SXR"),
        new PostalSpec("180001", "Jammu", "IN", "JK", "JK-IXJ"),
        // Puducherry
        new PostalSpec("605001", "Puducherry", "IN", "PY", "PY-PNY"),
        // North-East + hill/island states
        new PostalSpec("791111", "Itanagar", "IN", "AR", "AR-ITA"),
        new PostalSpec("795001", "Imphal", "IN", "MN", "MN-IMF"),
        new PostalSpec("793001", "Shillong", "IN", "ML", "ML-SHL"),
        new PostalSpec("796001", "Aizawl", "IN", "MZ", "MZ-AJL"),
        new PostalSpec("797001", "Kohima", "IN", "NL", "NL-KOH"),
        new PostalSpec("737101", "Gangtok", "IN", "SK", "SK-GTK"),
        new PostalSpec("799001", "Agartala", "IN", "TR", "TR-IXA"),
        new PostalSpec("744101", "Port Blair", "IN", "AN", "AN-IXZ"),
        new PostalSpec("194101", "Leh", "IN", "LA", "LA-IXL"),
        new PostalSpec("682555", "Kavaratti", "IN", "LD", "LD-KAV"),
        new PostalSpec("396210", "Daman", "IN", "DH", "DH-DMN"),
    };
}
